application: iamwjlee
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: hello2.application
# Handling web forms with webapp2  
libraries:  
- name: webapp2
  version: latest
